version: '3.9'
services:
  db:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db:
