version: '3.9'
services:
  db:
    image: mysql:8.1
    container_name: rematest-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  front:
    build:
      context: ./front
    ports:
      - 80:8080

  back:
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
