name: CD

on:
  push:
    branches: [ "qa" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    
    - run: docker compose build

    - run: docker image ls
    
    - run: docker image tag rematest-back spypah/testing-back
    - run: docker image tag rematest-front spypah/testing-front
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: spypah/testing-back:latest
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: spypah/testing-front:latest
  deploy:
    runs-on: ubuntu
    steps:
    - name: pull from docker hub
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: cd ~/dev/RemaTest ; docker compose up
        use_insecure_cipher: true
